### ISSUE TITLE
Optional async function to populate the Store before Server Side Rendering

### ISSUE THREAD

**Issue by gionatan-lombardi** [gionatan-lombardi/express-react-redux#1]
If the APP gets its contents from an API service (e.g. a CMS), this feature will be very useful if, for SEO reasons, this data must be displayed in the first Server Side Render.

**Comment by gionatan-lombardi** [comment]
@dai-shi I know I'm stressing you but if you have time can you give a look at this commit
9e87c896a42561d4041ba9737f1f3e514df2ea98 ?

If few word I've set another option: **beforeRenderPromise**. The default value is a resolved Promise with a `false` value, but the lib user can throw a self provided Promise whose result can trigger a redux dispatch before the Server Sider Rendering, in order to populate the App state.

The test pass but you know better than me the library and perhaps you can see some hidden problems in this solution.

Thanx in advance!

**Comment by dai-shi** [comment]
Hi, honestly I think the way you are trying is a bit complex to provide little flexibility. What if a user wants to call dispatch twice. Plus, somebody may want to call async functions based on `req.url`.
I'd want to make the library thin by avoiding such complexity. Let me think about what can be done.

**Comment by gionatan-lombardi** [comment]
Hi, you're right and now I pass the `req` Object directly in the Promise. I've made a commit with this and added this feature in the test: 5c80c0837f60068640aa246a3fa40c5095171f02.

For multiple fetch I'm just working on it because it's exactly what I need.

**Comment by gionatan-lombardi** [comment]
@dai-shi I've enhanced the test simulating multiple `fetch`.
The result is commit: bf680dd30c89e2373aadd5a8d08f70ed735c4e51

**Comment by dai-shi** [comment]
compare view: https://github.com/gionatan-lombardi/express-react-redux/compare/d52b541dde7a170cf7f745e834f573b85928a770...bf680dd30c89e2373aadd5a8d08f70ed735c4e51?w=1

You are doing a great job @gionatan-lombardi 

I would like to have two requests if I were to merge your patch.
1. make it more flexible by passing store.
2. accept callback-style as well as promise.

The code would look like this:
```
  beforeRender: (store, req, cb) => cb(),

...

  const store = createStore(reducer);
  const render = (err) => {
    if (err) return next(err);
    const context = {};
    const appHtml = renderToString(
    ...
  };
  const promise = beforeRender(store, req, render);
  if (promise && promise.then) promise.then(() => render(), err => render(err));
```

**Comment by dai-shi** [comment]
Should we change `beforeRender` to `beforeSSR`?

**Comment by gionatan-lombardi** [comment]
@dai-shi I like a lot your pattern and I've implemented it: 4feaf703df7f8a7ffbfbccdf7ed343b03d60c89c, and of course beforeSSR suites more with the other new option.

**Comment by dai-shi** [comment]
https://github.com/gionatan-lombardi/express-react-redux/compare/d52b541...4feaf70?w=1

Looks good, and sounds good.

Could you create a PR please? @gionatan-lombardi 

BTW, testing with two async functions is not very important, so you can simplify it by just having one.

**Comment by gionatan-lombardi** [comment]
@dai-shi You're right with the single async function in the test.
If you agree before doing a PR I'll use the library in a real project I'm working on, in case some bugs emerges during the process.
I'll not take long, I think a week will be enough.

**Comment by gionatan-lombardi** [comment]
@dai-shi I've put everything in the last 2 commits. 

Sadly I'm now facing a greater issue emerged in my real world project: the `head` tag with dynamic `title` and `meta` fetched from a CMS API service.

Currently I'm looking to [react-helmet](https://github.com/nfl/react-helmet) for an answer.

**Comment by dai-shi** [comment]
@gionatan-lombardi Please make a PR for me and I will merge it. Thanks a lot for your work.

**Comment by gionatan-lombardi** [comment]
@dai-shi Done!
