### ISSUE TITLE
Dynamic head and meta tags

### ISSUE THREAD

**Issue by gionatan-lombardi** [gionatan-lombardi/express-react-redux#2]
The goal is to populate the `head` data dynamically (eg. from an CMS API serving system), before the SSR and directly in React when a page changes.

**Comment by gionatan-lombardi** [comment]
Currently I'm trying to use [react-helmet](https://github.com/nfl/react-helmet), with the aid of this [tutorial](https://blog.digitalkwarts.com/server-side-rendering-with-reactjs-react-router-v4-react-helmet-and-css-modules/).

**Comment by gionatan-lombardi** [comment]
@dai-shi Is there a way in your library to get the bundled .js filename (the final with the hash)?

**Comment by gionatan-lombardi** [comment]
@dai-shi I've implemented [react-helmet ](https://github.com/nfl/react-helmet).

Sadly Helmet can't be optional so I was forced to **remove the indexSSR option** 
and the **index.html template**: now the [final html](https://github.com/gionatan-lombardi/express-react-redux/blob/e07208e999d053bd25bf01e77dce99a4e7ac48d4/lib/main.js#L128) is the `return` string of the [template.js](https://github.com/gionatan-lombardi/express-react-redux/blob/master/lib/template.js) module.

The [current commit](https://github.com/gionatan-lombardi/express-react-redux/commit/e07208e999d053bd25bf01e77dce99a4e7ac48d4) works correctly in my real use case but not in the new test I've added and I can't find a solution.

The only thing I've found is that in the good working case the react-helmet library is correctly included once as a singleton instead in the Jest test environment it's imported twice as separate modules so the [main.js required Helmet](https://github.com/gionatan-lombardi/express-react-redux/blob/e07208e999d053bd25bf01e77dce99a4e7ac48d4/lib/main.js#L13) doesn't update it's status from the [App.jsx  imported](https://github.com/gionatan-lombardi/express-react-redux/blob/e07208e999d053bd25bf01e77dce99a4e7ac48d4/tests/files/src/client/App.jsx#L2) one.

I would be very grateful if you could give a look because I'm losing my head on it and still I can't find a solution.

**Comment by dai-shi** [comment]
Hi @gionatan-lombardi,

I assume you already first tried it, but the dependency on react-helmet is not a good idea as general middleware.

I would do something like this:
```
diff --git a/lib/main.js b/lib/main.js
index 1fdbf7c..4c72653 100644
--- a/lib/main.js
+++ b/lib/main.js
@@ -29,6 +29,7 @@ const defaultOptions = {
   webpackDevBuildCallback: () => console.log('webpack dev build done.'),
   indexSSR: false,
   beforeSSR: (store, req, cb) => cb(),
+  renderIndexHtml: null,
 };
 
 
@@ -104,6 +105,16 @@ function middleware(options = {}) {
     }
     return indexHtml;
   };
+  const renderIndexHtml = options.renderIndexHtml || (
+    (html, appHtml, state) => {
+      const appDiv = '<div id="app">';
+      html = html.replace(appDiv, appDiv + appHtml);
+      const preloadedState = `<script>window.__PRELOADED_STATE__=${serialize(state)}</script>`;
+      const scriptTag = '<script type';
+      html = html.replace(scriptTag, preloadedState + scriptTag);
+      return html;
+    }
+  );
   app.use((req, res, next) => {
     if (req.url === '/' && !options.indexSSR) return next();
     if (!options.isRoutingUrl(req.url, req)) return next();
@@ -122,11 +133,7 @@ function middleware(options = {}) {
         res.redirect(302, context.url);
       } else {
         let html = getIndexHtml();
-        const appDiv = '<div id="app">';
-        html = html.replace(appDiv, appDiv + appHtml);
-        const preloadedState = `<script>window.__PRELOADED_STATE__=${serialize(store.getState())}</script>`;
-        const scriptTag = '<script type';
-        html = html.replace(scriptTag, preloadedState + scriptTag);
+        html = renderIndexHtml(html, appHtml, store.getState());
         res.set('content-type', 'text/html');
         res.send(html);
       }
```
```

**Comment by gionatan-lombardi** [comment]
Hi @dai-shi ,
I think you're right, helmet must be optional.
I'll try to implement your solution: it goes in the right direction.

**Comment by gionatan-lombardi** [comment]
Hi @dai-shi ,
I've implemented the solution with [this commit](https://github.com/gionatan-lombardi/express-react-redux/commit/9015ff26dae408ac96a3591ef535514a342a56e1) and the [relative test](https://github.com/gionatan-lombardi/express-react-redux/commit/a4cee4586b9e1044322e74139ab4fea9cc232b2f).

It works fine in the tests and in my real world use case with Helmet.

Do you think it's a good solution?

**Comment by dai-shi** [comment]
I added comments in the commit.

**Comment by dai-shi** [comment]
> I need indexJsCompiler in order to have the js-bundle filename

Do you mean you don't want to use [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin), or do you have any reason that doesn't work?

If possible, I would like to hide the complexity of the hash bundle filename.

@gionatan-lombardi

**Comment by dai-shi** [comment]
Oh, sorry, your motivation is to use react-helmet.
And, I assume you want to use a hash bundle filename.
Otherwise, you could just remove the hash, or get the hash filename from the index.html.

**Comment by gionatan-lombardi** [comment]
@dai-shi Hi, yes I've considered to remove the hash but I don't like that solution due to file caching for the browser reasons.

In react-helmet there's no index.html need, the html string is builded on every get call.

I came to the solution of exposing `indexJsCompiler` because this gives great flexibility. We can't know in advance all the possible use cases, surely not only react-helmet, and exposing this internal can achieve that.

I think there's no need to care about security issues, you're already in you server and if you want to soot in your foot you can do it with or without the middleware.

**Comment by dai-shi** [comment]
The compiler only works with `dev`, and this library is for `dev` and `production`, so we can't rely on it.

As I see

https://github.com/gionatan-lombardi/express-react-redux/blob/a4cee4586b9e1044322e74139ab4fea9cc232b2f/tests/middleware.test.js#L145

This is already a hack, so you could do like
```
bundleJs = html.match(/<script type="text\/javascript" src="\/([0-9a-z]+-index\.js)">/)[1];
```

in `renderHtml` with the patch https://github.com/gionatan-lombardi/express-react-redux/issues/2#issuecomment-331057611

It doesn't look like an ideal solution, but just a toy though.

**Comment by gionatan-lombardi** [comment]
You're right it's only in `dev` and I can use your hack too.

Thanx a lot. This solves my issue!
